[versions]
kotlin = "1.9.10"
dokka = "1.8.20"
spotless = "6.20.0"
kover = "0.7.3"
jgitver = "0.9.1"


[libraries]
kotlin_gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin_serialization = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin" }
dokka = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "dokka" }
spotless = { module = "com.diffplug.spotless:spotless-plugin-gradle", version.ref = "spotless" }
kover = { module = "org.jetbrains.kotlinx:kover-gradle-plugin", version.ref = "kover" }
jgitver = { module = "fr.brouillard.oss.gradle:gradle-jgitver-plugin", version.ref = "jgitver" }